name: nmnh_ms_tools
channels:
- conda-forge
- default
dependencies:
- python>=3.11
- pip
- bibtexparser
- bs4
- dateparser
- geographiclib
- geopandas
- gliner
- html5lib
- inflect
- lxml
- matplotlib
- nameparser
- nltk
- numpy
- openpyxl
- pillow
- pyarrow=20.*
- pymongo
- pyproj
- pytz
- pyyaml
- requests
- requests-cache
- shapely
- six
- sqlalchemy
- titlecase
- unidecode
- pip:
  - xmu
